### ISSUE TITLE
freemyipod.org is down

### ISSUE THREAD

**Issue by RaiRod** [user890104/bootloader-ipodclassic-instructions#5]
Hello, I can't seem to access the site and sadly it  is the only place that hosts the files I need to upload the bootloader into my ipod 6g, since you created the software, is it possible for you to upload it somewhere else as they fix the site. Thank you.

**Comment by user890104** [comment]
Hello, the server had to be reinstalled, and the main website (wiki) is still not available. However the Rockbox bootloader instructions are available, and the files can be downloaded, despite the wiki being down.
Please use the link in the project description.

**Comment by user890104** [comment]
Website is up.
